browser_launcher.py:930:SB
--------------------------------------------------------------------
Last Page: https://cn.tradingview.com/symbols/BTCUSD/
 Duration: 139.53s
  Browser: Chrome 136.0.7103.114 / headless
   Driver: chromedriver 136.0.7103.92
Timestamp: 1747656221  (Unix Timestamp)
     Date: Monday, 19 May 2025
     Time: 8:03:41 PM  (CST, UTC+08:00)
--------------------------------------------------------------------
Traceback:
  Traceback (most recent call last):
  File "/Users/noah/Library/Python/3.9/lib/python/site-packages/seleniumbase/fixtures/base_case.py", line 264, in open
    self.driver.get(url)
  File "/Users/noah/Library/Python/3.9/lib/python/site-packages/seleniumbase/core/browser_launcher.py", line 5416, in <lambda>
    driver.get = lambda url: uc_special_open_if_cf(
  File "/Users/noah/Library/Python/3.9/lib/python/site-packages/seleniumbase/core/browser_launcher.py", line 447, in uc_special_open_if_cf
    driver.default_get(url)  # The original one
  File "/Users/noah/Library/Python/3.9/lib/python/site-packages/seleniumbase/undetected/__init__.py", line 401, in get
    return super().get(url)
  File "/Users/noah/Library/Python/3.9/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 473, in get
    self.execute(Command.GET, {"url": url})
  File "/Users/noah/Library/Python/3.9/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
  File "/Users/noah/Library/Python/3.9/lib/python/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_RESET
  (Session info: chrome=136.0.7103.114)
Stacktrace:
0   uc_driver                           0x0000000100e4a8b8 uc_driver + 5986488
1   uc_driver                           0x0000000100e419ea uc_driver + 5949930
2   uc_driver                           0x00000001008fa600 uc_driver + 415232
3   uc_driver                           0x00000001008f1473 uc_driver + 377971
4   uc_driver                           0x00000001008e2378 uc_driver + 316280
5   uc_driver                           0x00000001008e405d uc_driver + 323677
6   uc_driver                           0x00000001008e26fb uc_driver + 317179
7   uc_driver                           0x00000001008e2123 uc_driver + 315683
8   uc_driver                           0x00000001008e1e24 uc_driver + 314916
9   uc_driver                           0x00000001008dfccd uc_driver + 306381
10  uc_driver                           0x00000001008e048a uc_driver + 308362
11  uc_driver                           0x00000001008fdb79 uc_driver + 428921
12  uc_driver                           0x000000010099a185 uc_driver + 1069445
13  uc_driver                           0x0000000100972312 uc_driver + 906002
14  uc_driver                           0x0000000100999566 uc_driver + 1066342
15  uc_driver                           0x00000001009720e3 uc_driver + 905443
16  uc_driver                           0x000000010093e61d uc_driver + 693789
17  uc_driver                           0x000000010093f281 uc_driver + 696961
18  uc_driver                           0x0000000100e08580 uc_driver + 5715328
19  uc_driver                           0x0000000100e0c445 uc_driver + 5731397
20  uc_driver                           0x0000000100de2ed0 uc_driver + 5562064
21  uc_driver                           0x0000000100e0ce7b uc_driver + 5734011
22  uc_driver                           0x0000000100dd1de4 uc_driver + 5492196
23  uc_driver                           0x0000000100e2fa98 uc_driver + 5876376
24  uc_driver                           0x0000000100e2fc60 uc_driver + 5876832
25  uc_driver                           0x0000000100e415b1 uc_driver + 5948849
26  libsystem_pthread.dylib             0x00007ff8144dd4e1 _pthread_start + 125
27  libsystem_pthread.dylib             0x00007ff8144d8f6b thread_start + 15


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/noah/Desktop/code/python/实时显示价格.py", line 46, in get_gold_price
    sb.open(url)
  File "/Users/noah/Library/Python/3.9/lib/python/site-packages/seleniumbase/fixtures/base_case.py", line 283, in open
    self.driver.get(url)
  File "/Users/noah/Library/Python/3.9/lib/python/site-packages/seleniumbase/core/browser_launcher.py", line 5416, in <lambda>
    driver.get = lambda url: uc_special_open_if_cf(
  File "/Users/noah/Library/Python/3.9/lib/python/site-packages/seleniumbase/core/browser_launcher.py", line 447, in uc_special_open_if_cf
    driver.default_get(url)  # The original one
  File "/Users/noah/Library/Python/3.9/lib/python/site-packages/seleniumbase/undetected/__init__.py", line 401, in get
    return super().get(url)
  File "/Users/noah/Library/Python/3.9/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 473, in get
    self.execute(Command.GET, {"url": url})
  File "/Users/noah/Library/Python/3.9/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
  File "/Users/noah/Library/Python/3.9/lib/python/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_RESET
  (Session info: chrome=136.0.7103.114)
Stacktrace:
0   uc_driver                           0x0000000100e4a8b8 uc_driver + 5986488
1   uc_driver                           0x0000000100e419ea uc_driver + 5949930
2   uc_driver                           0x00000001008fa600 uc_driver + 415232
3   uc_driver                           0x00000001008f1473 uc_driver + 377971
4   uc_driver                           0x00000001008e2378 uc_driver + 316280
5   uc_driver                           0x00000001008e405d uc_driver + 323677
6   uc_driver                           0x00000001008e26fb uc_driver + 317179
7   uc_driver                           0x00000001008e2123 uc_driver + 315683
8   uc_driver                           0x00000001008e1e24 uc_driver + 314916
9   uc_driver                           0x00000001008dfccd uc_driver + 306381
10  uc_driver                           0x00000001008e048a uc_driver + 308362
11  uc_driver                           0x00000001008fdb79 uc_driver + 428921
12  uc_driver                           0x000000010099a185 uc_driver + 1069445
13  uc_driver                           0x0000000100972312 uc_driver + 906002
14  uc_driver                           0x0000000100999566 uc_driver + 1066342
15  uc_driver                           0x00000001009720e3 uc_driver + 905443
16  uc_driver                           0x000000010093e61d uc_driver + 693789
17  uc_driver                           0x000000010093f281 uc_driver + 696961
18  uc_driver                           0x0000000100e08580 uc_driver + 5715328
19  uc_driver                           0x0000000100e0c445 uc_driver + 5731397
20  uc_driver                           0x0000000100de2ed0 uc_driver + 5562064
21  uc_driver                           0x0000000100e0ce7b uc_driver + 5734011
22  uc_driver                           0x0000000100dd1de4 uc_driver + 5492196
23  uc_driver                           0x0000000100e2fa98 uc_driver + 5876376
24  uc_driver                           0x0000000100e2fc60 uc_driver + 5876832
25  uc_driver                           0x0000000100e415b1 uc_driver + 5948849
26  libsystem_pthread.dylib             0x00007ff8144dd4e1 _pthread_start + 125
27  libsystem_pthread.dylib             0x00007ff8144d8f6b thread_start + 15

